import { chromium } from './node_modules/playwright/index.mjs';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1920, height: 1080 } });
const erros = []; p.on('pageerror', e => erros.push(e.message));
let sse = 0;
p.on('request', r => { if (r.url().includes('/api/events')) sse++; });
await p.goto('http://127.0.0.1:5173/territorio.html?mode=historico&uf=MG&turn=1', { waitUntil: 'load' });
await p.waitForTimeout(9000);
console.log('conexões de evento:', sse, '| mapa:', await p.$$eval('canvas', c => c.length), '| ranking:', await p.$$eval('.list .crow, .list button', r => r.length));
console.log('erros:', erros);
await b.close();
